### ISSUE TITLE
Mismatch in the description and settings

### ISSUE THREAD

**Issue by mudrd8mz** [richardjonesnz/moodle_filter_simplequestion#1]
The plugin description at moodle.org/plugins reads:
```
The filter text is of the form {{QUESTION:linktext|xxx|display}} where xxx is ...
```
However, the default settings is that the start tag is just `{QUESTION:`.

So if users are following the description, they have an extra pair of curly braces there.

**Comment by richardjonesnz** [comment]
I've changed the default settings, thanks.  Will check all the other documentation.
