### ISSUE TITLE
In embed mode, the clickable is not only the button but the whole wrapping div

### ISSUE THREAD

**Issue by mudrd8mz** [richardjonesnz/moodle_filter_simplequestion#2]
In embed mode in the Boost theme, the link text appears as a button. But clickable is all the wrapping div (highlighted in red in the following screenshot), not just the button. So clicking anywhere to the block / row where the button is, opens the iframe.

![image](https://user-images.githubusercontent.com/85831/33427699-8967db12-d5c6-11e7-82d8-d1dbdaa4c74e.png)

**Comment by richardjonesnz** [comment]
OK noted and fixed, thanks.
