### ISSUE TITLE
Question lazy loading only after link has been pressed

### ISSUE THREAD

**Issue by mudrd8mz** [richardjonesnz/moodle_filter_simplequestion#3]
At the moment, the question is rendered all the time, regardless on whether the user actually clicks the toggle widget.

It could lazy load only when needed - in which case this may be relevant: https://docs.moodle.org/dev/Fragment

**Comment by richardjonesnz** [comment]
Thanks David.  I believe I have found a solution using button and panel id's passed to jQuery's slideToggle method (see amd/src).  Solves the issue of multiple embedded questions on the same page.  I have noted fragment for future use though.
